// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT
//
// Symbol-rename header for the MIOpen public/private library split. It is
// force-included (via the compiler's -include flag) into every translation
// unit of the private implementation library (MIOpen_private) when the split
// is enabled with MIOPEN_ENABLE_HIPDNN_WRAPPER. Each #define below renames a
// public C entry point to its _impl form, so the private library
// exports the implementation under _impl names and the public symbol surface
// in libMIOpen.so is left free for the wrapper (src/private/wrapper.cpp) to
// define as thin forwarding stubs.
//
// The header contains only preprocessor #defines, so it is safe to
// force-include across all private sources (C++, HIP, and assembled kernels)
// without pulling in any declarations. The MIOpen source tree is otherwise
// untouched, keeping the whole rename gated behind the build flag.
//
// This header is intentionally NOT installed.
//
// HAND-MAINTAINED. Whenever a MIOPEN_EXPORT function is added to, removed
// from, or has its signature changed in include/miopen/miopen.h, four
// artifacts must be updated in lockstep:
//
//   1. include/miopen/miopen.h            the public declaration
//   2. src/private/miopen_private_rename.h  this file: the #define
//   3. src/private/miopen_impl.h          the _impl declaration the wrapper
//                                         (and, later, the hipDNN provider)
//                                         compiles against
//   4. src/private/wrapper.cpp            the forwarding stub
//
// The name half of this invariant is enforced by script/check_public_abi.py in
// CI: an added or dropped public symbol turns the baseline gate red. The
// signature half is NOT enforced anywhere -- these are extern "C" declarations,
// so a drifted signature links cleanly and misbehaves at run time.
#ifndef MIOPEN_PRIVATE_RENAME_H
#define MIOPEN_PRIVATE_RENAME_H

#ifndef MIOPEN_BUILDING_PRIVATE
#error "miopen_private_rename.h included outside of MIOpen Private build"
#endif

#define miopenGetErrorString miopenGetErrorString_impl
#define miopenGetVersion miopenGetVersion_impl
#define miopenCreate miopenCreate_impl
#define miopenCreateWithStream miopenCreateWithStream_impl
#define miopenDestroy miopenDestroy_impl
#define miopenSetStream miopenSetStream_impl
#define miopenGetStream miopenGetStream_impl
#define miopenSetAllocator miopenSetAllocator_impl
#define miopenGetKernelTime miopenGetKernelTime_impl
#define miopenEnableProfiling miopenEnableProfiling_impl
#define miopenCreateTensorDescriptor miopenCreateTensorDescriptor_impl
#define miopenSet4dTensorDescriptor miopenSet4dTensorDescriptor_impl
#define miopenSetNdTensorDescriptorWithLayout miopenSetNdTensorDescriptorWithLayout_impl
#define miopenSet4dTensorDescriptorEx miopenSet4dTensorDescriptorEx_impl
#define miopenGet4dTensorDescriptor miopenGet4dTensorDescriptor_impl
#define miopenSetTensorDescriptor miopenSetTensorDescriptor_impl
#define miopenSetTensorDescriptorV2 miopenSetTensorDescriptorV2_impl
#define miopenSetTensorCastType miopenSetTensorCastType_impl
#define miopenGetTensorDescriptorSize miopenGetTensorDescriptorSize_impl
#define miopenGetTensorDescriptor miopenGetTensorDescriptor_impl
#define miopenDestroyTensorDescriptor miopenDestroyTensorDescriptor_impl
#define miopenCreateSeqTensorDescriptor miopenCreateSeqTensorDescriptor_impl
#define miopenDestroySeqTensorDescriptor miopenDestroySeqTensorDescriptor_impl
#define miopenOpTensor miopenOpTensor_impl
#define miopenSetTensor miopenSetTensor_impl
#define miopenScaleTensor miopenScaleTensor_impl
#define miopenGetTensorNumBytes miopenGetTensorNumBytes_impl
#define miopenTransformTensor miopenTransformTensor_impl
#define miopenCreateConvolutionDescriptor miopenCreateConvolutionDescriptor_impl
#define miopenInitConvolutionDescriptor miopenInitConvolutionDescriptor_impl
#define miopenInitConvolutionNdDescriptor miopenInitConvolutionNdDescriptor_impl
#define miopenGetConvolutionSpatialDim miopenGetConvolutionSpatialDim_impl
#define miopenGetConvolutionDescriptor miopenGetConvolutionDescriptor_impl
#define miopenGetConvolutionNdDescriptor miopenGetConvolutionNdDescriptor_impl
#define miopenGetConvolutionGroupCount miopenGetConvolutionGroupCount_impl
#define miopenSetConvolutionGroupCount miopenSetConvolutionGroupCount_impl
#define miopenSetTransposeConvOutputPadding miopenSetTransposeConvOutputPadding_impl
#define miopenSetTransposeConvNdOutputPadding miopenSetTransposeConvNdOutputPadding_impl
#define miopenGetConvolutionForwardOutputDim miopenGetConvolutionForwardOutputDim_impl
#define miopenGetConvolutionNdForwardOutputDim miopenGetConvolutionNdForwardOutputDim_impl
#define miopenDestroyConvolutionDescriptor miopenDestroyConvolutionDescriptor_impl
#define miopenSetConvolutionAttribute miopenSetConvolutionAttribute_impl
#define miopenGetConvolutionAttribute miopenGetConvolutionAttribute_impl
#define miopenSetConvolutionFindMode miopenSetConvolutionFindMode_impl
#define miopenGetConvolutionFindMode miopenGetConvolutionFindMode_impl
#define miopenConvolutionForwardGetSolutionCount miopenConvolutionForwardGetSolutionCount_impl
#define miopenConvolutionForwardGetSolution miopenConvolutionForwardGetSolution_impl
#define miopenConvolutionForwardGetSolutionWorkspaceSize \
    miopenConvolutionForwardGetSolutionWorkspaceSize_impl
#define miopenConvolutionForwardCompileSolution miopenConvolutionForwardCompileSolution_impl
#define miopenConvolutionForwardImmediate miopenConvolutionForwardImmediate_impl
#define miopenConvolutionBackwardDataGetSolutionCount \
    miopenConvolutionBackwardDataGetSolutionCount_impl
#define miopenConvolutionBackwardDataGetSolution miopenConvolutionBackwardDataGetSolution_impl
#define miopenConvolutionBackwardDataGetSolutionWorkspaceSize \
    miopenConvolutionBackwardDataGetSolutionWorkspaceSize_impl
#define miopenConvolutionBackwardDataCompileSolution \
    miopenConvolutionBackwardDataCompileSolution_impl
#define miopenConvolutionBackwardDataImmediate miopenConvolutionBackwardDataImmediate_impl
#define miopenConvolutionBackwardWeightsGetSolutionCount \
    miopenConvolutionBackwardWeightsGetSolutionCount_impl
#define miopenConvolutionBackwardWeightsGetSolution miopenConvolutionBackwardWeightsGetSolution_impl
#define miopenConvolutionBackwardWeightsGetSolutionWorkspaceSize \
    miopenConvolutionBackwardWeightsGetSolutionWorkspaceSize_impl
#define miopenConvolutionBackwardWeightsCompileSolution \
    miopenConvolutionBackwardWeightsCompileSolution_impl
#define miopenConvolutionBackwardWeightsImmediate miopenConvolutionBackwardWeightsImmediate_impl
#define miopenConvolutionForwardGetWorkSpaceSize miopenConvolutionForwardGetWorkSpaceSize_impl
#define miopenFindConvolutionForwardAlgorithm miopenFindConvolutionForwardAlgorithm_impl
#define miopenConvolutionForward miopenConvolutionForward_impl
#define miopenConvolutionForwardBias miopenConvolutionForwardBias_impl
#define miopenConvolutionBackwardDataGetWorkSpaceSize \
    miopenConvolutionBackwardDataGetWorkSpaceSize_impl
#define miopenFindConvolutionBackwardDataAlgorithm miopenFindConvolutionBackwardDataAlgorithm_impl
#define miopenConvolutionBackwardData miopenConvolutionBackwardData_impl
#define miopenConvolutionBackwardWeightsGetWorkSpaceSize \
    miopenConvolutionBackwardWeightsGetWorkSpaceSize_impl
#define miopenFindConvolutionBackwardWeightsAlgorithm \
    miopenFindConvolutionBackwardWeightsAlgorithm_impl
#define miopenConvolutionBackwardWeights miopenConvolutionBackwardWeights_impl
#define miopenConvolutionBackwardBias miopenConvolutionBackwardBias_impl
#define miopenCreatePoolingDescriptor miopenCreatePoolingDescriptor_impl
#define miopenSetPoolingIndexType miopenSetPoolingIndexType_impl
#define miopenGetPoolingIndexType miopenGetPoolingIndexType_impl
#define miopenSetPoolingWorkSpaceIndexMode miopenSetPoolingWorkSpaceIndexMode_impl
#define miopenGetPoolingWorkSpaceIndexMode miopenGetPoolingWorkSpaceIndexMode_impl
#define miopenSet2dPoolingDescriptor miopenSet2dPoolingDescriptor_impl
#define miopenGet2dPoolingDescriptor miopenGet2dPoolingDescriptor_impl
#define miopenGetPoolingForwardOutputDim miopenGetPoolingForwardOutputDim_impl
#define miopenSetNdPoolingDescriptor miopenSetNdPoolingDescriptor_impl
#define miopenGetNdPoolingDescriptor miopenGetNdPoolingDescriptor_impl
#define miopenGetPoolingNdForwardOutputDim miopenGetPoolingNdForwardOutputDim_impl
#define miopenPoolingGetWorkSpaceSize miopenPoolingGetWorkSpaceSize_impl
#define miopenPoolingGetWorkSpaceSizeV2 miopenPoolingGetWorkSpaceSizeV2_impl
#define miopenPoolingForward miopenPoolingForward_impl
#define miopenPoolingBackward miopenPoolingBackward_impl
#define miopenDestroyPoolingDescriptor miopenDestroyPoolingDescriptor_impl
#define miopenCreateLRNDescriptor miopenCreateLRNDescriptor_impl
#define miopenSetLRNDescriptor miopenSetLRNDescriptor_impl
#define miopenGetLRNDescriptor miopenGetLRNDescriptor_impl
#define miopenLRNGetWorkSpaceSize miopenLRNGetWorkSpaceSize_impl
#define miopenLRNForward miopenLRNForward_impl
#define miopenLRNBackward miopenLRNBackward_impl
#define miopenDestroyLRNDescriptor miopenDestroyLRNDescriptor_impl
#define miopenLayerNormForward miopenLayerNormForward_impl
#define miopenGetLayerNormBackwardWorkspaceSize miopenGetLayerNormBackwardWorkspaceSize_impl
#define miopenLayerNormBackward miopenLayerNormBackward_impl
#define miopenCatForward miopenCatForward_impl
#define miopenDeriveBNTensorDescriptor miopenDeriveBNTensorDescriptor_impl
#define miopenBatchNormalizationForwardTraining miopenBatchNormalizationForwardTraining_impl
#define miopenBatchNormalizationForwardTraining_V2 miopenBatchNormalizationForwardTraining_V2_impl
#define miopenBatchNormalizationForwardTraining_V3 miopenBatchNormalizationForwardTraining_V3_impl
#define miopenBatchNormForwardTrainingActivation miopenBatchNormForwardTrainingActivation_impl
#define miopenBatchNormForwardTrainingActivation_V2 miopenBatchNormForwardTrainingActivation_V2_impl
#define miopenBatchNormalizationForwardInference miopenBatchNormalizationForwardInference_impl
#define miopenBatchNormalizationForwardInference_V2 miopenBatchNormalizationForwardInference_V2_impl
#define miopenBatchNormalizationForwardInferenceInvVariance \
    miopenBatchNormalizationForwardInferenceInvVariance_impl
#define miopenBatchNormForwardInferenceActivationInvVariance \
    miopenBatchNormForwardInferenceActivationInvVariance_impl
#define miopenBatchNormForwardInferenceActivation miopenBatchNormForwardInferenceActivation_impl
#define miopenBatchNormalizationBackward miopenBatchNormalizationBackward_impl
#define miopenBatchNormalizationBackward_V2 miopenBatchNormalizationBackward_V2_impl
#define miopenBatchNormBackwardActivation miopenBatchNormBackwardActivation_impl
#define miopenCreateActivationDescriptor miopenCreateActivationDescriptor_impl
#define miopenSetActivationDescriptor miopenSetActivationDescriptor_impl
#define miopenGetActivationDescriptor miopenGetActivationDescriptor_impl
#define miopenActivationForward miopenActivationForward_impl
#define miopenActivationBackward miopenActivationBackward_impl
#define miopenDestroyActivationDescriptor miopenDestroyActivationDescriptor_impl
#define miopenGLUForward miopenGLUForward_impl
#define miopenGLUBackward miopenGLUBackward_impl
#define miopenSoftmaxForward miopenSoftmaxForward_impl
#define miopenSoftmaxBackward miopenSoftmaxBackward_impl
#define miopenSoftmaxForward_V2 miopenSoftmaxForward_V2_impl
#define miopenSoftmaxBackward_V2 miopenSoftmaxBackward_V2_impl
#define miopenCreateFusionPlan miopenCreateFusionPlan_impl
#define miopenDestroyFusionPlan miopenDestroyFusionPlan_impl
#define miopenCompileFusionPlan miopenCompileFusionPlan_impl
#define miopenFusionPlanGetOp miopenFusionPlanGetOp_impl
#define miopenFusionPlanGetWorkSpaceSize miopenFusionPlanGetWorkSpaceSize_impl
#define miopenFusionPlanConvolutionGetAlgo miopenFusionPlanConvolutionGetAlgo_impl
#define miopenFusionPlanConvolutionSetAlgo miopenFusionPlanConvolutionSetAlgo_impl
#define miopenCreateOpConvForward miopenCreateOpConvForward_impl
#define miopenCreateOpActivationForward miopenCreateOpActivationForward_impl
#define miopenCreateOpActivationBackward miopenCreateOpActivationBackward_impl
#define miopenCreateOpBiasForward miopenCreateOpBiasForward_impl
#define miopenCreateOpBatchNormInference miopenCreateOpBatchNormInference_impl
#define miopenCreateOpBatchNormForward miopenCreateOpBatchNormForward_impl
#define miopenCreateOpBatchNormBackward miopenCreateOpBatchNormBackward_impl
#define miopenCreateOperatorArgs miopenCreateOperatorArgs_impl
#define miopenDestroyOperatorArgs miopenDestroyOperatorArgs_impl
#define miopenSetOpArgsConvForward miopenSetOpArgsConvForward_impl
#define miopenSetOpArgsActivForward miopenSetOpArgsActivForward_impl
#define miopenSetOpArgsActivBackward miopenSetOpArgsActivBackward_impl
#define miopenSetOpArgsBatchNormInference miopenSetOpArgsBatchNormInference_impl
#define miopenSetOpArgsBatchNormForward miopenSetOpArgsBatchNormForward_impl
#define miopenSetOpArgsBatchNormBackward miopenSetOpArgsBatchNormBackward_impl
#define miopenSetOpArgsBiasForward miopenSetOpArgsBiasForward_impl
#define miopenExecuteFusionPlan miopenExecuteFusionPlan_impl
#define miopenExecuteFusionPlan_v2 miopenExecuteFusionPlan_v2_impl
#define miopenConvolutionBiasActivationForward miopenConvolutionBiasActivationForward_impl
#define miopenCreateRNNDescriptor miopenCreateRNNDescriptor_impl
#define miopenGetRNNDescriptor miopenGetRNNDescriptor_impl
#define miopenGetRNNDescriptor_V2 miopenGetRNNDescriptor_V2_impl
#define miopenDestroyRNNDescriptor miopenDestroyRNNDescriptor_impl
#define miopenSetRNNDescriptor miopenSetRNNDescriptor_impl
#define miopenSetRNNDescriptor_V2 miopenSetRNNDescriptor_V2_impl
#define miopenSetRNNDataSeqTensorDescriptor miopenSetRNNDataSeqTensorDescriptor_impl
#define miopenGetRNNDataSeqTensorDescriptor miopenGetRNNDataSeqTensorDescriptor_impl
#define miopenGetRNNWorkspaceSize miopenGetRNNWorkspaceSize_impl
#define miopenGetRNNTrainingReserveSize miopenGetRNNTrainingReserveSize_impl
#define miopenGetRNNTempSpaceSizes miopenGetRNNTempSpaceSizes_impl
#define miopenGetRNNParamsSize miopenGetRNNParamsSize_impl
#define miopenGetRNNParamsDescriptor miopenGetRNNParamsDescriptor_impl
#define miopenGetRNNInputTensorSize miopenGetRNNInputTensorSize_impl
#define miopenGetRNNHiddenTensorSize miopenGetRNNHiddenTensorSize_impl
#define miopenGetRNNLayerParamSize miopenGetRNNLayerParamSize_impl
#define miopenGetRNNLayerBiasSize miopenGetRNNLayerBiasSize_impl
#define miopenGetRNNLayerParam miopenGetRNNLayerParam_impl
#define miopenGetRNNLayerBias miopenGetRNNLayerBias_impl
#define miopenGetRNNLayerParamOffset miopenGetRNNLayerParamOffset_impl
#define miopenGetRNNLayerBiasOffset miopenGetRNNLayerBiasOffset_impl
#define miopenSetRNNLayerParam miopenSetRNNLayerParam_impl
#define miopenSetRNNLayerBias miopenSetRNNLayerBias_impl
#define miopenSetRNNPaddingMode miopenSetRNNPaddingMode_impl
#define miopenGetRNNPaddingMode miopenGetRNNPaddingMode_impl
#define miopenRNNForward miopenRNNForward_impl
#define miopenRNNBackwardSeqData miopenRNNBackwardSeqData_impl
#define miopenRNNBackwardWeightsSeqTensor miopenRNNBackwardWeightsSeqTensor_impl
#define miopenRNNForwardTraining miopenRNNForwardTraining_impl
#define miopenRNNBackwardData miopenRNNBackwardData_impl
#define miopenRNNBackwardWeights miopenRNNBackwardWeights_impl
#define miopenRNNForwardInference miopenRNNForwardInference_impl
#define miopenCreateCTCLossDescriptor miopenCreateCTCLossDescriptor_impl
#define miopenGetCTCLossDescriptor miopenGetCTCLossDescriptor_impl
#define miopenDestroyCTCLossDescriptor miopenDestroyCTCLossDescriptor_impl
#define miopenSetCTCLossDescriptor miopenSetCTCLossDescriptor_impl
#define miopenGetCTCLossWorkspaceSize miopenGetCTCLossWorkspaceSize_impl
#define miopenCTCLoss miopenCTCLoss_impl
#define miopenCreateDropoutDescriptor miopenCreateDropoutDescriptor_impl
#define miopenDestroyDropoutDescriptor miopenDestroyDropoutDescriptor_impl
#define miopenDropoutGetReserveSpaceSize miopenDropoutGetReserveSpaceSize_impl
#define miopenDropoutGetStatesSize miopenDropoutGetStatesSize_impl
#define miopenGetDropoutDescriptor miopenGetDropoutDescriptor_impl
#define miopenRestoreDropoutDescriptor miopenRestoreDropoutDescriptor_impl
#define miopenSetDropoutDescriptor miopenSetDropoutDescriptor_impl
#define miopenDropoutForward miopenDropoutForward_impl
#define miopenDropoutBackward miopenDropoutBackward_impl
#define miopenCreateReduceTensorDescriptor miopenCreateReduceTensorDescriptor_impl
#define miopenDestroyReduceTensorDescriptor miopenDestroyReduceTensorDescriptor_impl
#define miopenSetReduceTensorDescriptor miopenSetReduceTensorDescriptor_impl
#define miopenGetReduceTensorDescriptor miopenGetReduceTensorDescriptor_impl
#define miopenGetReductionIndicesSize miopenGetReductionIndicesSize_impl
#define miopenGetReductionWorkspaceSize miopenGetReductionWorkspaceSize_impl
#define miopenReduceTensor miopenReduceTensor_impl
#define miopenCreateConvProblem miopenCreateConvProblem_impl
#define miopenCreateMhaProblem miopenCreateMhaProblem_impl
#define miopenCreateMhaDescriptor miopenCreateMhaDescriptor_impl
#define miopenSetMhaDescriptor miopenSetMhaDescriptor_impl
#define miopenGetMhaDescriptor miopenGetMhaDescriptor_impl
#define miopenCreateSoftmaxDescriptor miopenCreateSoftmaxDescriptor_impl
#define miopenSetSoftmaxDescriptor miopenSetSoftmaxDescriptor_impl
#define miopenGetSoftmaxDescriptor miopenGetSoftmaxDescriptor_impl
#define miopenDestroyProblem miopenDestroyProblem_impl
#define miopenSetProblemTensorDescriptor miopenSetProblemTensorDescriptor_impl
#define miopenCreateFindOptions miopenCreateFindOptions_impl
#define miopenDestroyFindOptions miopenDestroyFindOptions_impl
#define miopenSetFindOptionTuning miopenSetFindOptionTuning_impl
#define miopenSetFindOptionResultsOrder miopenSetFindOptionResultsOrder_impl
#define miopenSetFindOptionWorkspaceLimit miopenSetFindOptionWorkspaceLimit_impl
#define miopenSetFindOptionPreallocatedWorkspace miopenSetFindOptionPreallocatedWorkspace_impl
#define miopenSetFindOptionPreallocatedTensor miopenSetFindOptionPreallocatedTensor_impl
#define miopenSetFindOptionAttachBinaries miopenSetFindOptionAttachBinaries_impl
#define miopenFindSolutions miopenFindSolutions_impl
#define miopenRunSolution miopenRunSolution_impl
#define miopenDestroySolution miopenDestroySolution_impl
#define miopenLoadSolution miopenLoadSolution_impl
#define miopenSaveSolution miopenSaveSolution_impl
#define miopenGetSolutionSize miopenGetSolutionSize_impl
#define miopenGetSolutionWorkspaceSize miopenGetSolutionWorkspaceSize_impl
#define miopenGetSolutionTime miopenGetSolutionTime_impl
#define miopenGetSolutionSolverId miopenGetSolutionSolverId_impl
#define miopenGetSolverIdConvAlgorithm miopenGetSolverIdConvAlgorithm_impl
#define miopenCreateActivationProblem miopenCreateActivationProblem_impl
#define miopenCreateBatchnormProblem miopenCreateBatchnormProblem_impl
#define miopenFuseProblems miopenFuseProblems_impl
#define miopenCreateBiasProblem miopenCreateBiasProblem_impl
#define miopenCreateSoftmaxProblem miopenCreateSoftmaxProblem_impl
#define miopenGetReduceCalculationWorkspaceSize miopenGetReduceCalculationWorkspaceSize_impl
#define miopenReduceCalculationForward miopenReduceCalculationForward_impl
#define miopenReduceExtremeForward miopenReduceExtremeForward_impl
#define miopenGroupNormForward miopenGroupNormForward_impl
#define miopenAddLayerNormForward miopenAddLayerNormForward_impl
#define miopenT5LayerNormForward miopenT5LayerNormForward_impl
#define miopenGetT5LayerNormBackwardWorkspaceSize miopenGetT5LayerNormBackwardWorkspaceSize_impl
#define miopenT5LayerNormBackward miopenT5LayerNormBackward_impl
#define miopenFusedAdam miopenFusedAdam_impl
#define miopenFusedAdamWithOutput miopenFusedAdamWithOutput_impl
#define miopenTransformersAdamW miopenTransformersAdamW_impl
#define miopenTransformersAdamWWithOutput miopenTransformersAdamWWithOutput_impl
#define miopenGetGetitemWorkspaceSize miopenGetGetitemWorkspaceSize_impl
#define miopenGetitemBackward miopenGetitemBackward_impl
#define miopenRoPEForward miopenRoPEForward_impl
#define miopenRoPEBackward miopenRoPEBackward_impl
#define miopenKthvalueForward miopenKthvalueForward_impl
#define miopenGetPReLUBackwardWorkspaceSize miopenGetPReLUBackwardWorkspaceSize_impl
#define miopenPReLUBackward miopenPReLUBackward_impl
#define miopenGetSoftMarginLossForwardWorkspaceSize miopenGetSoftMarginLossForwardWorkspaceSize_impl
#define miopenSoftMarginLossForward miopenSoftMarginLossForward_impl
#define miopenSoftMarginLossBackward miopenSoftMarginLossBackward_impl
#define miopenGetMultiMarginLossForwardWorkspaceSize \
    miopenGetMultiMarginLossForwardWorkspaceSize_impl
#define miopenMultiMarginLossForward miopenMultiMarginLossForward_impl
#define miopenSetTuningPolicy miopenSetTuningPolicy_impl
#define miopenGetTuningPolicy miopenGetTuningPolicy_impl

#endif // MIOPEN_PRIVATE_RENAME_H
