// Copyright (c) 2022-2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SEGMENTED_REDUCE_HPP_
#define ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SEGMENTED_REDUCE_HPP_

#include "../../../type_traits.hpp"
#include "../device_config_helper.hpp"

#include <type_traits>

/* DO NOT EDIT THIS FILE
 * This file is automatically generated by `/scripts/autotune/create_optimization.py`.
 * so most likely you want to edit rocprim/device/device_(algo)_config.hpp
 */

/// \addtogroup primitivesmodule_deviceconfigs
/// @{

BEGIN_ROCPRIM_NAMESPACE

namespace detail
{
// TARGET: {'gen': 'rdna2', 'arch': 'gfx1030', 'gpu': 'rx6900', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'rdna3', 'arch': 'gfx1100', 'gpu': 'rx7900', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'gcn5', 'arch': 'gfx906', 'gpu': 'mi50', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 8}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'cdna1', 'arch': 'gfx908', 'gpu': 'mi100', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 8}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 128, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {128, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'cdna2', 'arch': 'gfx90a', 'gpu': 'mi210', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'rdna4', 'arch': 'gfx1201', 'gpu': 'rx9070', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna4, target_arch::gfx1201, gpu::rx9070, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'cdna3', 'arch': 'gfx942', 'gpu': 'mi300x', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>>::value,
    reduce_config_params>
{
    // CONFIG: {'key_type': 'double', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'float', 'block_size_x': 256, 'ipt': 8}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16}
    if constexpr((bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 16)
                  && (sizeof(key_type) > 8)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int64_t', 'block_size_x': 256, 'ipt': 16}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 8)
                  && (sizeof(key_type) > 4)))
    {
        return reduce_config_params{
            {256, 16},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 4)
                  && (sizeof(key_type) > 2)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'short', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 2)
                  && (sizeof(key_type) > 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // CONFIG: {'key_type': 'int8_t', 'block_size_x': 256, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<key_type>::value) && (sizeof(key_type) <= 1)))
    {
        return reduce_config_params{
            {256, 8},
            ::rocprim::block_reduce_algorithm::using_warp_reduce
        };
    }
    // Default case if none of the conditions match
    return reduce_config_params_base<key_type>();
}

// TARGET: {'gen': 'unknown', 'arch': 'unknown', 'gpu': 'generic', 'rep': 'amdgcn'}
template<class Target, class key_type>
constexpr auto segmented_reduce_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>::value,
    reduce_config_params>
{
    return segmented_reduce_config_picker<
        comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
        key_type>();
}

// All the existing configs should be auto generated
using segmented_reduce_targets
    = comp_targets<comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>,
                   comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>,
                   comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>,
                   comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
                   comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>,
                   comp_target<gen::rdna4, target_arch::gfx1201, gpu::rx9070, rep::amdgcn>,
                   comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>,
                   comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>;

} // end namespace detail

END_ROCPRIM_NAMESPACE

/// @}
// end of group primitivesmodule_deviceconfigs

#endif // ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SEGMENTED_REDUCE_HPP_
