// Copyright (c) 2022-2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SCAN_HPP_
#define ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SCAN_HPP_

#include "../../../config.hpp"
#include "../../../type_traits.hpp"
#include "../../config_types.hpp"
#include "../device_config_helper.hpp"

#include <type_traits>

/* DO NOT EDIT THIS FILE
 * This file is automatically generated by `/scripts/autotune/create_optimization.py`.
 * so most likely you want to edit rocprim/device/device_(algo)_config.hpp
 */

/// \addtogroup primitivesmodule_deviceconfigs
/// @{

BEGIN_ROCPRIM_NAMESPACE

namespace detail
{
// TARGET: {'gen': 'rdna2', 'arch': 'gfx1030', 'gpu': 'rx6900', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 128, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {128, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 64, 'ipt': 5, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {64, 5},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 64, 'ipt': 12, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {64, 12},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 2, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {256, 2},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 4, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 4},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 64, 'ipt': 5, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {64, 5},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 64, 'ipt': 12, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {64, 12},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'rdna3', 'arch': 'gfx1100', 'gpu': 'rx7900', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 4, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 4},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 64, 'ipt': 22, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {64, 22},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 8, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {256, 8},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 4, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 4},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 64, 'ipt': 22, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {64, 22},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'rdna4', 'arch': 'gfx1200', 'gpu': 'rx9060', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna4, target_arch::gfx1200, gpu::rx9060, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 8, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 8},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 4, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 4},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 8, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 8},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'rdna4', 'arch': 'gfx1201', 'gpu': 'rx9070', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna4, target_arch::gfx1201, gpu::rx9070, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 6, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 6},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 12, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {256, 12},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 16, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 16},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 6, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 6},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 256, 'ipt': 12, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {256, 12},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 11, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {256, 11},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'gcn5', 'arch': 'gfx906', 'gpu': 'mi50', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 128, 'ipt': 10, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {128, 10},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 64, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {64, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 64, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {64, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'cdna1', 'arch': 'gfx908', 'gpu': 'mi100', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 256, 'ipt': 6, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 6},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 128, 'ipt': 10, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {128, 10},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 6, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 6},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 128, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {128, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'cdna2', 'arch': 'gfx90a', 'gpu': 'mi210', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 128, 'ipt': 10, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {128, 10},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 128, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {128, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 64, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {64, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 64, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {64, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 128, 'ipt': 7, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {128, 7},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 128, 'ipt': 10, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {128, 10},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 64, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {64, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'cdna3', 'arch': 'gfx942', 'gpu': 'mi300x', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>>::value,
    scan_config_params>
{
    // CONFIG: {'value_type': 'double', 'block_size_x': 256, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'float', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 14, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 16)
                  && (sizeof(value_type) > 8)))
    {
        return scan_config_params{
            {256, 14},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int64_t', 'block_size_x': 256, 'ipt': 15, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::reduce_then_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 8)
                  && (sizeof(value_type) > 4)))
    {
        return scan_config_params{
            {256, 15},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::reduce_then_scan
        };
    }
    // CONFIG: {'value_type': 'int', 'block_size_x': 256, 'ipt': 21, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 4)
                  && (sizeof(value_type) > 2)))
    {
        return scan_config_params{
            {256, 21},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'short', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value) && (sizeof(value_type) <= 2)
                  && (sizeof(value_type) > 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // CONFIG: {'value_type': 'int8_t', 'block_size_x': 256, 'ipt': 24, 'block_load_method': '::rocprim::block_load_method::block_load_transpose', 'block_store_method': '::rocprim::block_store_method::block_store_transpose', 'block_scan_algo': '::rocprim::block_scan_algorithm::using_warp_scan'}
    if constexpr((!bool(rocprim::is_floating_point<value_type>::value)
                  && (sizeof(value_type) <= 1)))
    {
        return scan_config_params{
            {256, 24},
            ::rocprim::block_load_method::block_load_transpose,
            ::rocprim::block_store_method::block_store_transpose,
            block_scan_algorithm::using_warp_scan
        };
    }
    // Default case if none of the conditions match
    return scan_config_params_base<value_type>();
}

// TARGET: {'gen': 'unknown', 'arch': 'unknown', 'gpu': 'generic', 'rep': 'amdgcn'}
template<class Target, class value_type>
constexpr auto scan_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>::value,
    scan_config_params>
{
    return scan_config_picker<comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
                              value_type>();
}

// All the existing configs should be auto generated
using scan_targets
    = comp_targets<comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>,
                   comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>,
                   comp_target<gen::rdna4, target_arch::gfx1200, gpu::rx9060, rep::amdgcn>,
                   comp_target<gen::rdna4, target_arch::gfx1201, gpu::rx9070, rep::amdgcn>,
                   comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>,
                   comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
                   comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>,
                   comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>,
                   comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>;

} // end namespace detail

END_ROCPRIM_NAMESPACE

/// @}
// end of group primitivesmodule_deviceconfigs

#endif // ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_SCAN_HPP_
