# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""HIP R0600 device properties from ``hip/hip_runtime_api.h``.

Field names, order, and C types match ``hipDeviceProp_tR0600``. Bind this
structure only to ``hipGetDevicePropertiesR0600``; the unversioned legacy
function writes a different layout. Reserved fields are part of the ABI.
"""

import ctypes


class _HipUUID(ctypes.Structure):
    _fields_ = [("bytes", ctypes.c_char * 16)]


class _HipDeviceArch(ctypes.Structure):
    _fields_ = [
        ("hasGlobalInt32Atomics", ctypes.c_uint, 1),
        ("hasGlobalFloatAtomicExch", ctypes.c_uint, 1),
        ("hasSharedInt32Atomics", ctypes.c_uint, 1),
        ("hasSharedFloatAtomicExch", ctypes.c_uint, 1),
        ("hasFloatAtomicAdd", ctypes.c_uint, 1),
        ("hasGlobalInt64Atomics", ctypes.c_uint, 1),
        ("hasSharedInt64Atomics", ctypes.c_uint, 1),
        ("hasDoubles", ctypes.c_uint, 1),
        ("hasWarpVote", ctypes.c_uint, 1),
        ("hasWarpBallot", ctypes.c_uint, 1),
        ("hasWarpShuffle", ctypes.c_uint, 1),
        ("hasFunnelShift", ctypes.c_uint, 1),
        ("hasThreadFenceSystem", ctypes.c_uint, 1),
        ("hasSyncThreadsExt", ctypes.c_uint, 1),
        ("hasSurfaceFuncs", ctypes.c_uint, 1),
        ("has3dGrid", ctypes.c_uint, 1),
        ("hasDynamicParallelism", ctypes.c_uint, 1),
    ]


class HipDevicePropR0600(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char * 256),
        ("uuid", _HipUUID),
        ("luid", ctypes.c_char * 8),
        ("luidDeviceNodeMask", ctypes.c_uint),
        ("totalGlobalMem", ctypes.c_size_t),
        ("sharedMemPerBlock", ctypes.c_size_t),
        ("regsPerBlock", ctypes.c_int),
        ("warpSize", ctypes.c_int),
        ("memPitch", ctypes.c_size_t),
        ("maxThreadsPerBlock", ctypes.c_int),
        ("maxThreadsDim", ctypes.c_int * 3),
        ("maxGridSize", ctypes.c_int * 3),
        ("clockRate", ctypes.c_int),
        ("totalConstMem", ctypes.c_size_t),
        ("major", ctypes.c_int),
        ("minor", ctypes.c_int),
        ("textureAlignment", ctypes.c_size_t),
        ("texturePitchAlignment", ctypes.c_size_t),
        ("deviceOverlap", ctypes.c_int),
        ("multiProcessorCount", ctypes.c_int),
        ("kernelExecTimeoutEnabled", ctypes.c_int),
        ("integrated", ctypes.c_int),
        ("canMapHostMemory", ctypes.c_int),
        ("computeMode", ctypes.c_int),
        ("maxTexture1D", ctypes.c_int),
        ("maxTexture1DMipmap", ctypes.c_int),
        ("maxTexture1DLinear", ctypes.c_int),
        ("maxTexture2D", ctypes.c_int * 2),
        ("maxTexture2DMipmap", ctypes.c_int * 2),
        ("maxTexture2DLinear", ctypes.c_int * 3),
        ("maxTexture2DGather", ctypes.c_int * 2),
        ("maxTexture3D", ctypes.c_int * 3),
        ("maxTexture3DAlt", ctypes.c_int * 3),
        ("maxTextureCubemap", ctypes.c_int),
        ("maxTexture1DLayered", ctypes.c_int * 2),
        ("maxTexture2DLayered", ctypes.c_int * 3),
        ("maxTextureCubemapLayered", ctypes.c_int * 2),
        ("maxSurface1D", ctypes.c_int),
        ("maxSurface2D", ctypes.c_int * 2),
        ("maxSurface3D", ctypes.c_int * 3),
        ("maxSurface1DLayered", ctypes.c_int * 2),
        ("maxSurface2DLayered", ctypes.c_int * 3),
        ("maxSurfaceCubemap", ctypes.c_int),
        ("maxSurfaceCubemapLayered", ctypes.c_int * 2),
        ("surfaceAlignment", ctypes.c_size_t),
        ("concurrentKernels", ctypes.c_int),
        ("ECCEnabled", ctypes.c_int),
        ("pciBusID", ctypes.c_int),
        ("pciDeviceID", ctypes.c_int),
        ("pciDomainID", ctypes.c_int),
        ("tccDriver", ctypes.c_int),
        ("asyncEngineCount", ctypes.c_int),
        ("unifiedAddressing", ctypes.c_int),
        ("memoryClockRate", ctypes.c_int),
        ("memoryBusWidth", ctypes.c_int),
        ("l2CacheSize", ctypes.c_int),
        ("persistingL2CacheMaxSize", ctypes.c_int),
        ("maxThreadsPerMultiProcessor", ctypes.c_int),
        ("streamPrioritiesSupported", ctypes.c_int),
        ("globalL1CacheSupported", ctypes.c_int),
        ("localL1CacheSupported", ctypes.c_int),
        ("sharedMemPerMultiprocessor", ctypes.c_size_t),
        ("regsPerMultiprocessor", ctypes.c_int),
        ("managedMemory", ctypes.c_int),
        ("isMultiGpuBoard", ctypes.c_int),
        ("multiGpuBoardGroupID", ctypes.c_int),
        ("hostNativeAtomicSupported", ctypes.c_int),
        ("singleToDoublePrecisionPerfRatio", ctypes.c_int),
        ("pageableMemoryAccess", ctypes.c_int),
        ("concurrentManagedAccess", ctypes.c_int),
        ("computePreemptionSupported", ctypes.c_int),
        ("canUseHostPointerForRegisteredMem", ctypes.c_int),
        ("cooperativeLaunch", ctypes.c_int),
        ("cooperativeMultiDeviceLaunch", ctypes.c_int),
        ("sharedMemPerBlockOptin", ctypes.c_size_t),
        ("pageableMemoryAccessUsesHostPageTables", ctypes.c_int),
        ("directManagedMemAccessFromHost", ctypes.c_int),
        ("maxBlocksPerMultiProcessor", ctypes.c_int),
        ("accessPolicyMaxWindowSize", ctypes.c_int),
        ("reservedSharedMemPerBlock", ctypes.c_size_t),
        ("hostRegisterSupported", ctypes.c_int),
        ("sparseHipArraySupported", ctypes.c_int),
        ("hostRegisterReadOnlySupported", ctypes.c_int),
        ("timelineSemaphoreInteropSupported", ctypes.c_int),
        ("memoryPoolsSupported", ctypes.c_int),
        ("gpuDirectRDMASupported", ctypes.c_int),
        ("gpuDirectRDMAFlushWritesOptions", ctypes.c_uint),
        ("gpuDirectRDMAWritesOrdering", ctypes.c_int),
        ("memoryPoolSupportedHandleTypes", ctypes.c_uint),
        ("deferredMappingHipArraySupported", ctypes.c_int),
        ("ipcEventSupported", ctypes.c_int),
        ("clusterLaunch", ctypes.c_int),
        ("unifiedFunctionPointers", ctypes.c_int),
        ("reserved", ctypes.c_int * 63),
        ("hipReserved", ctypes.c_int * 32),
        ("gcnArchName", ctypes.c_char * 256),
        ("maxSharedMemoryPerMultiProcessor", ctypes.c_size_t),
        ("clockInstructionRate", ctypes.c_int),
        ("arch", _HipDeviceArch),
        ("hdpMemFlushCntl", ctypes.POINTER(ctypes.c_uint)),
        ("hdpRegFlushCntl", ctypes.POINTER(ctypes.c_uint)),
        ("cooperativeMultiDeviceUnmatchedFunc", ctypes.c_int),
        ("cooperativeMultiDeviceUnmatchedGridDim", ctypes.c_int),
        ("cooperativeMultiDeviceUnmatchedBlockDim", ctypes.c_int),
        ("cooperativeMultiDeviceUnmatchedSharedMem", ctypes.c_int),
        ("isLargeBar", ctypes.c_int),
        ("asicRevision", ctypes.c_int),
    ]
