// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

// See graph.fbs for the semantics of this annotation.
attribute "cache_uid";

namespace hipdnn_flatbuffers_sdk.data_objects;

table RMSNormBackwardAttributes {
    dy_tensor_uid: long (cache_uid);
    x_tensor_uid: long (cache_uid);
    scale_tensor_uid: long (cache_uid);
    inv_rms_tensor_uid: long (cache_uid);
    dx_tensor_uid: long (cache_uid);
    dscale_tensor_uid: long (cache_uid);
    dbias_tensor_uid: long = null (cache_uid);
}
