// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

include "norm_common.fbs";

// See graph.fbs for the semantics of this annotation.
attribute "cache_uid";

namespace hipdnn_flatbuffers_sdk.data_objects;

table RMSNormAttributes {
    x_tensor_uid: long (cache_uid);
    scale_tensor_uid: long (cache_uid);
    epsilon_tensor_uid: long (cache_uid);
    y_tensor_uid: long (cache_uid);
    bias_tensor_uid: long = null (cache_uid);
    inv_rms_tensor_uid: long = null (cache_uid);
    forward_phase: NormFwdPhase = NOT_SET;
}
