#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Create a per-worktree Python venv, sharing a heavy base venv when it helps.

Editable installs of compiled packages write a *global* finder into the active
venv's site-packages, and that finder hard-codes one build directory. Sharing a
venv across git worktrees therefore means whichever worktree installed last
wins; the others silently import its binary.

Two machine shapes are handled differently:

  pip wheel SDK   ~11GB inside a venv -> worktree venv shares the base venv's
                  site-packages, and reaches the toolchain through the base
                  venv's console-script trampolines.
  system install  already outside any venv -> plain standalone worktree venv.

Cross-platform: bin vs Scripts and lib/pythonX.Y vs Lib are resolved by asking
each interpreter for its own sysconfig paths.
"""

from __future__ import annotations

import argparse
import glob as _glob_mod
import json
import os
import shutil
import subprocess
import sys
import venv
from pathlib import Path

_MODULE_NAME = "_worktree_base_env"
# .pth files are processed in sorted order; zz_ keeps this last.
_PTH_NAME = "zz_worktree_base_env.pth"

# Consulted only after probing real binaries. Legacy layouts.
_FALLBACK_GLOBS = {
    "nt": [r"C:\Program Files\AMD\ROCm\*"],
    "posix": ["/opt/rocm", "/opt/rocm-*", "/usr/local/rocm", "/usr/local/rocm-*"],
}

# Binaries that mark a ROCm root, found at <root>/bin/<name>.
_MARKER_BINARIES = ("amdclang++", "hipcc", "hipconfig")

_BOOTSTRAP_HEADER = """\
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# Auto-generated by skills/worktree-venv. Do not edit.
#
# Imported from {pth_name} at interpreter startup, so it applies to every entry
# point -- python, pytest, IDE runners, and anything they spawn -- not just an
# activated shell.

import os
import sys
"""

_SHARE_BLOCK = """

# Reach the base venv's heavy dependencies without copying them. Appended,
# never inserted, so a package installed in this worktree always wins.
BASE_SITE_PACKAGES = r"{base_sp}"
if BASE_SITE_PACKAGES not in sys.path:
    sys.path.append(BASE_SITE_PACKAGES)
"""

_ROCM_BLOCK = """

# Pin the ROCm toolchain this venv was configured against. With
# editable.rebuild, CMake runs on plain `import`, so this must hold for
# non-shell entry points too. setdefault: an explicit ROCM_PATH still wins.
ROCM_PATH = r"{rocm_root}"
# NOT necessarily <root>/bin. For the pip SDK, bin/ holds trampolines that
# resolve the real tools at runtime; the raw <root>/bin binaries are not
# directly executable (amdclang++ there dies with "could not exec amdllvm").
ROCM_BIN = r"{rocm_bin}"
ROCM_CMAKE = r"{cmake_prefix}"

if os.path.isdir(ROCM_PATH):
    os.environ.setdefault("ROCM_PATH", ROCM_PATH)

# Insert ROCM_BIN *after* this venv's own bin, never before it. For the pip SDK
# ROCM_BIN is the base venv's bin, which also contains pip/python/invoke --
# putting it first makes `pip install -e` write into the BASE venv, silently
# defeating the whole point of a per-worktree venv.
_own_bin = os.path.join(sys.prefix, "Scripts" if os.name == "nt" else "bin")
_parts = [p for p in os.environ.get("PATH", "").split(os.pathsep) if p]
# Also covers the unactivated case (venv/bin/python -m invoke), where this
# venv's bin is not on PATH at all and ROCM_BIN would otherwise land first.
if os.path.isdir(_own_bin) and _own_bin not in _parts:
    _parts.insert(0, _own_bin)
if os.path.isdir(ROCM_BIN) and ROCM_BIN not in _parts:
    _parts.insert(_parts.index(_own_bin) + 1 if _own_bin in _parts else 0, ROCM_BIN)
os.environ["PATH"] = os.pathsep.join(_parts)
if ROCM_CMAKE and ROCM_CMAKE not in os.environ.get("CMAKE_PREFIX_PATH", "").split(os.pathsep):
    _existing = os.environ.get("CMAKE_PREFIX_PATH", "")
    os.environ["CMAKE_PREFIX_PATH"] = (
        ROCM_CMAKE + os.pathsep + _existing if _existing else ROCM_CMAKE
    )
"""


def _venv_python(venv_dir: Path) -> Path:
    for rel in ("bin/python", "bin/python3", "Scripts/python.exe"):
        candidate = venv_dir / rel
        if candidate.exists():
            return candidate
    raise SystemExit(f"no interpreter found under {venv_dir}")


def _site_packages(python: Path) -> Path:
    """Ask an interpreter where its own purelib is (handles both platforms)."""
    out = subprocess.run(
        [
            str(python),
            "-c",
            "import json,sysconfig; print(json.dumps(sysconfig.get_paths()))",
        ],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return Path(json.loads(out)["purelib"])


def _rocm_sdk_query(bin_dir: Path, what: str) -> Path | None:
    """`rocm-sdk path --<what>` -- authoritative for the pip SDK."""
    exe = shutil.which("rocm-sdk", path=str(bin_dir))
    if not exe:
        return None
    try:
        out = subprocess.run(
            [exe, "path", f"--{what}"], capture_output=True, text=True, check=True
        ).stdout.strip()
    except subprocess.CalledProcessError:
        return None
    return Path(out) if out else None


def _root_from_binary(name: str) -> Path | None:
    """Resolve <root> from <root>/bin/<name> via a PATH lookup."""
    found = shutil.which(name)
    if not found:
        return None
    resolved = Path(found).resolve()
    return resolved.parent.parent if resolved.parent.name.lower() == "bin" else None


def _classify(root: Path) -> str:
    parts = {p.lower() for p in root.parts}
    return (
        "wheel"
        if "site-packages" in parts or root.name == "_rocm_sdk_devel"
        else "system"
    )


def detect_rocm(base_bin: Path | None, override: str | None) -> tuple[str, Path | None]:
    """Locate ROCm and classify it as "wheel" or "system".

    Probes the rocm-sdk CLI, then $ROCM_PATH, then real binaries on PATH, then
    a short list of legacy locations. Never guesses beyond that -- the caller
    prompts instead.
    """
    if override:
        root = Path(override).expanduser().resolve()
        if not root.is_dir():
            raise SystemExit(f"--rocm-path does not exist: {root}")
        return _classify(root), root

    if base_bin:
        root = _rocm_sdk_query(base_bin, "root")
        if root and root.is_dir():
            return "wheel", root

    env = os.environ.get("ROCM_PATH")
    if env and Path(env).is_dir():
        root = Path(env).resolve()
        return _classify(root), root

    for name in _MARKER_BINARIES:
        root = _root_from_binary(name)
        if root and root.is_dir():
            return _classify(root), root

    for pattern in _FALLBACK_GLOBS["nt" if os.name == "nt" else "posix"]:
        for match in sorted((Path(p) for p in _glob_mod.glob(pattern)), reverse=True):
            if match.is_dir():
                return _classify(match), match

    return "none", None


def _prompt_for_rocm() -> Path:
    if not sys.stdin.isatty():
        raise SystemExit(
            "ROCm not found (probed rocm-sdk, ROCM_PATH, PATH, default locations).\n"
            "Re-run with --rocm-path <root>."
        )
    print("Could not locate ROCm automatically. Probed: rocm-sdk CLI, $ROCM_PATH,")
    print(f"  {', '.join(_MARKER_BINARIES)} on PATH,")
    print(f"  {', '.join(_FALLBACK_GLOBS['nt' if os.name == 'nt' else 'posix'])}")
    while True:
        answer = input("ROCm root (blank to abort): ").strip()
        if not answer:
            raise SystemExit("aborted")
        root = Path(answer).expanduser().resolve()
        if root.is_dir():
            return root
        print(f"  not a directory: {root}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("worktree", type=Path, help="git worktree root")
    parser.add_argument(
        "--base-venv",
        type=Path,
        default=Path(os.environ.get("BASE_VENV", Path.home() / ".venv")),
        help="venv holding the shared heavy dependencies (default: $BASE_VENV or ~/.venv)",
    )
    parser.add_argument(
        "--name", default=".venv", help="venv dir name (default: .venv)"
    )
    parser.add_argument("--rocm-path", help="ROCm root; skips detection")
    parser.add_argument(
        "--standalone", action="store_true", help="never share the base venv"
    )
    args = parser.parse_args()

    worktree = args.worktree.resolve()
    if not worktree.is_dir():
        raise SystemExit(f"not a directory: {worktree}")

    base_venv = args.base_venv.resolve()
    base_python = _venv_python(base_venv) if base_venv.is_dir() else None
    base_bin = base_python.parent if base_python else None

    kind, rocm_root = detect_rocm(base_bin, args.rocm_path)
    if kind == "none":
        rocm_root = _prompt_for_rocm()
        kind = _classify(rocm_root)

    if kind == "wheel":
        # The trampolines live in the base venv's bin, not <root>/bin.
        rocm_bin = base_bin
        cmake_prefix = _rocm_sdk_query(base_bin, "cmake") if base_bin else None
    else:
        rocm_bin = rocm_root / "bin"
        cmake_prefix = rocm_root / "lib" / "cmake"

    # Only the pip SDK justifies sharing: it is huge and lives inside the base
    # venv. A system install is already outside any venv.
    share = kind == "wheel" and not args.standalone
    base_sp = _site_packages(base_python) if share else None

    target = worktree / args.name
    if target.exists():
        raise SystemExit(f"already exists, refusing to overwrite: {target}")

    print(f"ROCm    : {kind} at {rocm_root}")
    print(f"  bin   : {rocm_bin}")
    print(f"  cmake : {cmake_prefix}")
    print(f"creating {target} ({'sharing base venv' if share else 'standalone'})")
    venv.EnvBuilder(with_pip=True, symlinks=os.name != "nt").create(target)

    local_sp = _site_packages(_venv_python(target))

    body = _BOOTSTRAP_HEADER.format(pth_name=_PTH_NAME)
    if share:
        body += _SHARE_BLOCK.format(base_sp=base_sp)
    if rocm_root:
        body += _ROCM_BLOCK.format(
            rocm_root=rocm_root,
            rocm_bin=rocm_bin or "",
            cmake_prefix=cmake_prefix or "",
        )
    (local_sp / f"{_MODULE_NAME}.py").write_text(body)
    (local_sp / _PTH_NAME).write_text(f"import {_MODULE_NAME}\n")

    if share:
        print(f"  base site-packages: {base_sp}")
    else:
        print("  standalone: install this project's requirements.txt into the venv")
    print()
    activate = target / ("Scripts/activate" if os.name == "nt" else "bin/activate")
    print(f"next: source {activate}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
