// Copyright (c) 2022-2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_PARTITION_TWO_WAY_PREDICATE_HPP_
#define ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_PARTITION_TWO_WAY_PREDICATE_HPP_

#include "../../../config.hpp"
#include "../../../type_traits.hpp"
#include "../../config_types.hpp"
#include "../device_config_helper.hpp"

#include <type_traits>

/* DO NOT EDIT THIS FILE
 * This file is automatically generated by `/scripts/autotune/create_optimization.py`.
 * so most likely you want to edit rocprim/device/device_(algo)_config.hpp
 */

/// \addtogroup primitivesmodule_deviceconfigs
/// @{

BEGIN_ROCPRIM_NAMESPACE

namespace detail
{
// TARGET: {'gen': 'rdna2', 'arch': 'gfx1030', 'gpu': 'rx6900', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 512, 'ipt': 4}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 512, 'ipt': 4}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 512, 'ipt': 8}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {512, 8}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {256, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 512, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 512, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 128, 'ipt': 30}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {128, 30}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'rdna3', 'arch': 'gfx1100', 'gpu': 'rx7900', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 512, 'ipt': 8}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 8}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 192, 'ipt': 9}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {192, 9}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 192, 'ipt': 12}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {192, 12}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 512, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 512, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 8}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 128, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {128, 8}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 128, 'ipt': 18}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {128, 18}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 256, 'ipt': 28}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {256, 28}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'rdna4', 'arch': 'gfx1200', 'gpu': 'rx9060', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::rdna4, target_arch::gfx1200, gpu::rx9060, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 256, 'ipt': 4}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {256, 4}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 384, 'ipt': 6}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {384, 6}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 384, 'ipt': 18}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {384, 18}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 512, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 4}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 512, 'ipt': 8}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {512, 8}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 384, 'ipt': 18}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {384, 18}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 384, 'ipt': 28}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {384, 28}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'gcn5', 'arch': 'gfx906', 'gpu': 'mi50', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 256, 'ipt': 7}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {256, 7}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 256, 'ipt': 15}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {256, 15}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 26}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {256, 26}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 256, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {256, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 256, 'ipt': 7}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {256, 7}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 192, 'ipt': 15}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {192, 15}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'cdna1', 'arch': 'gfx908', 'gpu': 'mi100', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 128, 'ipt': 7}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {128, 7}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 256, 'ipt': 15}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {256, 15}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 26}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {256, 26}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 128, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {128, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 128, 'ipt': 7}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {128, 7}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 256, 'ipt': 13}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {256, 13}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'cdna2', 'arch': 'gfx90a', 'gpu': 'mi210', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 128, 'ipt': 6}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {128, 6}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 256, 'ipt': 10}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {256, 10}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 256, 'ipt': 20}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {256, 20}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 128, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {128, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 192, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {192, 4}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 256, 'ipt': 10}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {256, 10}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 256, 'ipt': 28}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {256, 28}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 256, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {256, 24}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'cdna3', 'arch': 'gfx942', 'gpu': 'mi300x', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>>::value,
    partition_config_params>
{
    // CONFIG: {'data_type': 'double', 'block_size_x': 512, 'ipt': 7}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 7}
        };
    }
    // CONFIG: {'data_type': 'float', 'block_size_x': 512, 'ipt': 15}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {512, 15}
        };
    }
    // CONFIG: {'data_type': 'rocprim::half', 'block_size_x': 512, 'ipt': 30}
    if constexpr((bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)))
    {
        return partition_config_params{
            {512, 30}
        };
    }
    // CONFIG: {'data_type': 'rocprim::int128_t', 'block_size_x': 384, 'ipt': 4}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 16)
                  && (sizeof(data_type) > 8)))
    {
        return partition_config_params{
            {384, 4}
        };
    }
    // CONFIG: {'data_type': 'int64_t', 'block_size_x': 512, 'ipt': 7}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 8)
                  && (sizeof(data_type) > 4)))
    {
        return partition_config_params{
            {512, 7}
        };
    }
    // CONFIG: {'data_type': 'int', 'block_size_x': 512, 'ipt': 15}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 4)
                  && (sizeof(data_type) > 2)))
    {
        return partition_config_params{
            {512, 15}
        };
    }
    // CONFIG: {'data_type': 'short', 'block_size_x': 512, 'ipt': 30}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 2)
                  && (sizeof(data_type) > 1)))
    {
        return partition_config_params{
            {512, 30}
        };
    }
    // CONFIG: {'data_type': 'int8_t', 'block_size_x': 512, 'ipt': 24}
    if constexpr((!bool(rocprim::is_floating_point<data_type>::value) && (sizeof(data_type) <= 1)))
    {
        return partition_config_params{
            {512, 24}
        };
    }
    // Default case if none of the conditions match
    return partition_config_params_base<data_type>();
}

// TARGET: {'gen': 'unknown', 'arch': 'unknown', 'gpu': 'generic', 'rep': 'amdgcn'}
template<class Target, class data_type>
constexpr auto partition_two_way_predicate_config_picker() -> std::enable_if_t<
    std::is_same<Target,
                 comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>::value,
    partition_config_params>
{
    return partition_two_way_predicate_config_picker<
        comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
        data_type>();
}

// All the existing configs should be auto generated
using partition_two_way_predicate_targets
    = comp_targets<comp_target<gen::rdna2, target_arch::gfx1030, gpu::rx6900, rep::amdgcn>,
                   comp_target<gen::rdna3, target_arch::gfx1100, gpu::rx7900, rep::amdgcn>,
                   comp_target<gen::rdna4, target_arch::gfx1200, gpu::rx9060, rep::amdgcn>,
                   comp_target<gen::gcn5, target_arch::gfx906, gpu::mi50, rep::amdgcn>,
                   comp_target<gen::cdna1, target_arch::gfx908, gpu::mi100, rep::amdgcn>,
                   comp_target<gen::cdna2, target_arch::gfx90a, gpu::mi210, rep::amdgcn>,
                   comp_target<gen::cdna3, target_arch::gfx942, gpu::mi300x, rep::amdgcn>,
                   comp_target<gen::unknown, target_arch::unknown, gpu::generic, rep::amdgcn>>;

} // end namespace detail

END_ROCPRIM_NAMESPACE

/// @}
// end of group primitivesmodule_deviceconfigs

#endif // ROCPRIM_DEVICE_DETAIL_CONFIG_DEVICE_PARTITION_TWO_WAY_PREDICATE_HPP_
