# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: shared/primbench/docs/conf.py

python:
  install:
    - requirements: shared/primbench/docs/sphinx/requirements.txt

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
  jobs:
    pre_build:
      - cd shared/primbench/docs/doxygen && doxygen Doxyfile
